OPENAI_API_KEY = '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'

[connections.snowflake]
user = "farhun04"
password = "Farhun04#.."
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"
account = "odjdltw-keb25559"